kind: ConfigMap
apiVersion: v1
metadata:
  name: compositions-row-column-datalist
  namespace: {{ .Release.Namespace }}
data:
  width: "24"
  prefix: "compositions-row-column-datalist"
  asGrid: "false"
---
apiVersion: templates.krateo.io/v1alpha1
kind: CollectionIterator
metadata:
  name: compositions-row-column-datalist
  namespace: {{ .Release.Namespace }}
spec:
  type: datalist
  propsRef:
    name: compositions-row-column-datalist
    namespace: {{ .Release.Namespace }}
  widgetsRefs:
  - iterator: .allCompositions.status.compositioncards
    template:
      apiVersion: templates.krateo.io/v1alpha1
      resource: widgets
      name: ${ .metadata.name }
      namespace: ${ .metadata.namespace }
  api:
  - name: allCompositions
    path: "/call?apiVersion=templates.krateo.io%2Fv1&resource=restactions&name=compositions&namespace={{ .Release.Namespace }}"
    verb: GET
    endpointRef:
      name: snowplow-endpoint
      namespace: {{ .Release.Namespace }}
    headers:
    - 'Accept: application/json'