kind: ConfigMap
apiVersion: v1
metadata:
  name: templates-row-column
  namespace: {{ .Release.Namespace }}
data:
  width: "8"
---
apiVersion: templates.krateo.io/v1alpha1
kind: CollectionIterator
metadata:
  name: templates-row-column
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/connector-verbose": "true"
spec:
  type: grid
  propsRef:
    name: templates-row-column
    namespace: {{ .Release.Namespace }}
  widgetsRefs:
  - iterator: .allCompositionDefinitions.items
    template:
      apiVersion: templates.krateo.io/v1alpha1
      resource: widgets
      name: ${ "template-" + .metadata.name + "-card" }
      namespace: ${ .metadata.namespace }
  api:
  - name: allCompositionDefinitions
    path: "/list?category=defs"
    verb: GET
    endpointRef:
      name: bff-endpoint
      namespace: {{ .Release.Namespace }}
    headers:
    - 'Accept: application/json'