kind: ConfigMap
apiVersion: v1
metadata:
  name: compositions-row-column
  namespace: {{ .Release.Namespace }}
data:
  width: "24"
---
apiVersion: templates.krateo.io/v1alpha1
kind: Collection
metadata:
  name: compositions-row-column
  namespace: {{ .Release.Namespace }}
spec:
  type: column
  propsRef:
    name: compositions-row-column
    namespace: {{ .Release.Namespace }}
  widgetsRefs:
  - apiVersion: templates.krateo.io/v1alpha1
    resource: widgets
    name: compositions-row-column-button
    namespace: {{ .Release.Namespace }}
  - apiVersion: templates.krateo.io/v1alpha1
    resource: collectioniterators
    name: compositions-row-column-datalist
    namespace: {{ .Release.Namespace }}