kind: ConfigMap
apiVersion: v1
metadata:
  name: compositions-row-column
  namespace: {{ .Release.Namespace }}
data:
  width: "24"
---
apiVersion: templates.krateo.io/v1alpha1
kind: CollectionIterator
metadata:
  name: compositions-row-column
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/connector-verbose": "true"
spec:
  type: column
  propsRef:
    name: compositions-row-column
    namespace: {{ .Release.Namespace }}
  widgetsRefs:
  - iterator: .allCompositions.items
    template:
      apiVersion: templates.krateo.io/v1alpha1
      resource: widgets
      name: ${ "composition-" + .metadata.name + "-card" }
      namespace: ${ .metadata.namespace }
  api:
  - name: allCompositions
    path: "/list?category=compositions"
    verb: GET
    endpointRef:
      name: bff-endpoint
      namespace: {{ .Release.Namespace }}
    headers:
    - 'Accept: application/json'