kind: ConfigMap
apiVersion: v1
metadata:
  name: menu
  namespace: {{ .Release.Namespace }}
data:
  default: "/compositions"
---
apiVersion: templates.krateo.io/v1alpha1
kind: Collection
metadata:
  name: menu
  namespace: krateo-system
spec:
  propsRef:
    name: menu
    namespace: {{ .Release.Namespace }}
  type: menu
  widgetsRefs:
  - apiVersion: templates.krateo.io/v1alpha1
    name: menu-templates
    namespace: krateo-system
    resource: widgets
  - apiVersion: templates.krateo.io/v1alpha1
    name: menu-compositions
    namespace: krateo-system
    resource: widgets
  - apiVersion: templates.krateo.io/v1alpha1
    name: menu-fake
    namespace: krateo-system
    resource: widgets