kind: ConfigMap
apiVersion: v1
metadata:
  name: templates-grid
  namespace: {{ .Release.Namespace }}
data:
  width: "12"
---
apiVersion: templates.krateo.io/v1alpha1
kind: CollectionIterator
metadata:
  name: templates-grid
  namespace: {{ .Release.Namespace }}
spec:
  type: grid
  propsRef:
    name: templates-grid
    namespace: {{ .Release.Namespace }}
  widgetsRefs:
  - iterator: .allCompositionDefinitions.status.templatecards
    template:
      apiVersion: templates.krateo.io/v1alpha1
      resource: widgets
      name: ${ .metadata.name }
      namespace: ${ .metadata.namespace }
  api:
  - name: allCompositionDefinitions
    path: "/call?apiVersion=templates.krateo.io%2Fv1&resource=restactions&name=templates&namespace={{ .Release.Namespace }}"
    verb: GET
    endpointRef:
      name: snowplow-endpoint
      namespace: {{ .Release.Namespace }}
    headers:
    - 'Accept: application/json'