apiVersion: templates.krateo.io/v1alpha1
kind: Collection
metadata:
  name: templates-row
  namespace: {{ .Release.Namespace }}
spec:
  type: row
  widgetsRefs:
  - apiVersion: templates.krateo.io/v1alpha1
    resource: collectioniterators
    name: templates-row-column
    namespace: {{ .Release.Namespace }}