apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tags.templates.krateo.io
spec:
  group: templates.krateo.io
  names:
    plural: tags
    singular: tag
    kind: Tag
    shortNames:
      - tg
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tags:
                  type: string
