apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: filters.templates.krateo.io
spec:
  group: templates.krateo.io
  names:
    plural: filters
    singular: filter
    kind: Filter
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tags:
                  type: string
                title:
                  type: string
                content:
                  type: string
                status:
                  type: string
                date:
                  type: string