apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: cyberjoker-password
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ randAlphaNum 12 | quote }}
---
apiVersion: basic.authn.krateo.io/v1alpha1
kind: User
metadata:
  name: cyberjoker
  namespace: {{ .Release.Namespace }}
spec:
  displayName: Cyber Joker
  avatarURL: https://i.pravatar.cc/256?img=70
  groups:
    - devs
  passwordRef:
    namespace: {{ .Release.Namespace }}
    name: cyberjoker-password
    key: password
---
# role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: templates-access-role
rules:
- apiGroups: ["templates.krateo.io"]
  resources: ["collections","widgets","form","forms","resourcetrees"]
  verbs: ["get", "list", "watch"]  # Adjust the verbs as needed (e.g., "create", "update", "delete")
---
# rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: templates-access-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: Group
  name: devs
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: templates-access-role
  apiGroup: rbac.authorization.k8s.io
---
# role-compositiondefinitions.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: compositiondefinitions-access-role
rules:
- apiGroups: ["core.krateo.io"]
  resources: ["compositiondefinitions"]
  verbs: ["get", "list", "watch"]  # Adjust the verbs as needed (e.g., "create", "update", "delete")
---
# rolebinding-compositiondefinitions.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: compositiondefinitions-access-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: Group
  name: devs
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: compositiondefinitions-access-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: compositions-creator
rules:
- apiGroups: ["composition.krateo.io"]
  resources: ["*"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: compositions-creator-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: Group
  name: devs
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: compositions-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: admin-password
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ randAlphaNum 12 | quote }}
---
apiVersion: basic.authn.krateo.io/v1alpha1
kind: User
metadata:
  name: admin
  namespace: {{ .Release.Namespace }}
spec:
  displayName: Admin
  avatarURL: https://i.pravatar.cc/256?img=69
  groups:
    - admins
  passwordRef:
    namespace: {{ .Release.Namespace }}
    name: admin-password
    key: password
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding
subjects:
- kind: Group
  name: admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
