apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: templates
  namespace: {{ .Release.Namespace }}
spec:
  api:
  - name: namespaces
    path: "/api/v1/namespaces"
    filter: "[.items[] | .metadata.name]"
  - name: templatecards
    dependsOn: 
      name: namespaces
      iterator: .[]
    path: ${ "/apis/templates.krateo.io/v1alpha1/namespaces/" + (.) + "/widgets" }
    filter: "[.items[] | select(.spec.type == \"card\" and (.metadata.name | startswith(\"template-\")))]"
    continueOnError: true