apiVersion: templates.krateo.io/v1alpha1
kind: Collection
metadata:
  name: templates-row
  namespace: {{ .Release.Namespace }}
spec:
  type: row
  widgetsRefs:
  - apiVersion: templates.krateo.io/v1alpha1
    resource: collections
    name: templates-row-column-1
    namespace: {{ .Release.Namespace }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: templates-row-column-1
  namespace: {{ .Release.Namespace }}
data:
  width: "24"
---
apiVersion: templates.krateo.io/v1alpha1
kind: Collection
metadata:
  name: templates-row-column-1
  namespace: {{ .Release.Namespace }}
spec:
  type: column
  propsRef:
    name: templates-row-column-1
    namespace: {{ .Release.Namespace }}
  widgetsRefs:
  - apiVersion: templates.krateo.io/v1alpha1
    resource: collectioniterators
    name: compositiondefinitions-grid
    namespace: {{ .Release.Namespace }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: compositiondefinitions-grid
  namespace: {{ .Release.Namespace }}
data:
  width: "8"
---
apiVersion: templates.krateo.io/v1alpha1
kind: CollectionIterator
metadata:
  name: compositiondefinitions-grid
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/connector-verbose": "true"
spec:
  type: grid
  propsRef:
    name: compositiondefinitions-grid
    namespace: {{ .Release.Namespace }}
  widgetsRefs:
  - iterator: .allCompositionDefinitions.items
    template:
      apiVersion: templates.krateo.io/v1alpha1
      resource: widgets
      name: ${ "template-" + .metadata.name + "-card" }
      namespace: ${ .metadata.namespace }
  api:
  - name: allCompositionDefinitions
    path: "/list?category=defs"
    verb: GET
    endpointRef:
      name: bff-endpoint
      namespace: {{ .Release.Namespace }}
    headers:
    - 'Accept: application/json'
---
apiVersion: templates.krateo.io/v1alpha1
kind: Collection
metadata:
  name: compositions-row
  namespace: {{ .Release.Namespace }}
spec:
  type: row
  widgetsRefs:
  - apiVersion: templates.krateo.io/v1alpha1
    resource: collectioniterators
    name: compositions-column
    namespace: {{ .Release.Namespace }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: compositions-column
  namespace: {{ .Release.Namespace }}
data:
  width: "24"
---
apiVersion: templates.krateo.io/v1alpha1
kind: CollectionIterator
metadata:
  name: compositions-column
  namespace: {{ .Release.Namespace }}
  annotations:
    "krateo.io/connector-verbose": "true"
spec:
  type: column
  propsRef:
    name: compositions-column
    namespace: {{ .Release.Namespace }}
  widgetsRefs:
  - iterator: .allCompositions.items
    template:
      apiVersion: templates.krateo.io/v1alpha1
      resource: widgets
      name: ${ "composition-" + .metadata.name + "-card" }
      namespace: ${ .metadata.namespace }
  api:
  - name: allCompositions
    path: "/list?category=compositions"
    verb: GET
    endpointRef:
      name: bff-endpoint
      namespace: {{ .Release.Namespace }}
    headers:
    - 'Accept: application/json'
---
