apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  name: menu-templates
  namespace: krateo-system
spec:
  actions:
  - template:
      apiVersion: templates.krateo.io/v1alpha1
      name: templates-row
      namespace: krateo-system
      resource: collections
      verb: GET
  app:
    template:
      icon: fa-gear
      label: Templates
      menu: "true"
      path: /templates
  type: route
