kind: ConfigMap
apiVersion: v1
metadata:
  name: compositions-row-column-button
  namespace: {{ .Release.Namespace }}
data:
  label: Filter
  verb: get
  prefix: "compositions-row-column-datalist"
  filter: "true"
  drawer: "true"
---
apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  name: compositions-row-column-button
  namespace: {{ .Release.Namespace }}
spec:
  type: button
  propsRef:
    name: compositions-row-column-button
    namespace: {{ .Release.Namespace }}
  actions:
  - template:
      apiVersion: templates.krateo.io/v1alpha1
      resource: customforms
      name: compositions-row-column-button-drawer-panel-customform
      namespace: {{ .Release.Namespace }}
      verb: GET