kind: ConfigMap
apiVersion: v1
metadata:
  name: compositions-row-column-button-drawer-panel-customform
  namespace: {{ .Release.Namespace }}
data:
  prefix: composition-list
---
apiVersion: templates.krateo.io/v1alpha1
kind: CustomForm
metadata:
  name: compositions-row-column-button-drawer-panel-customform
  namespace: {{ .Release.Namespace }}
spec:
  type: customform
  propsRef:
    name: compositions-row-column-button-drawer-panel-customform
    namespace: {{ .Release.Namespace }}
  app:
    template:
      schema: ${ .getFilters | .spec.versions[] | select(.name == "v1alpha1") | .schema.openAPIV3Schema.properties.spec }
  api:
  - name: getFilters
    path: "/apis/apiextensions.k8s.io/v1/customresourcedefinitions/tags.templates.krateo.io"
    verb: GET
    headers:
    - 'Accept: application/json'