apiVersion: templates.krateo.io/v1alpha1
kind: Widget
metadata:
  name: templates-route
  namespace: {{ .Release.Namespace }}
spec:
  app:
    template:
      endpoint: /call?resource=collectioniterators&apiVersion=templates.krateo.io/v1alpha1&name=templates-grid&namespace={{ .Release.Namespace }}
      icon: fa-rectangle-list
      label: Templates
      menu: "true"
      path: /templates
      order: "2"
  type: route